import enum


class CollectionKind(enum.StrEnum):
    STYLE_GUIDE = "STYLE_GUIDE"
    TECHNICAL_DOSSIER = "TECHNICAL_DOSSIER"


class DocumentType(enum.StrEnum):
    STYLE_GUIDE = "STYLE_GUIDE"
    TECHNICAL_SHEET = "TECHNICAL_SHEET"
    BLUEPRINT = "BLUEPRINT"
    ECO_CERTIFICATE = "ECO_CERTIFICATE"
    ASSEMBLY_NOTICE = "ASSEMBLY_NOTICE"
    MATERIAL_SPECIFICATION = "MATERIAL_SPECIFICATION"
    UNKNOWN = "UNKNOWN"


class StatutDocumentCollection(enum.StrEnum):
    EN_ATTENTE = "EN_ATTENTE"
    EN_COURS = "EN_COURS"
    A_VALIDER = "A_VALIDER"
    TERMINE = "TERMINE"
    ERREUR = "ERREUR"


class StatutDocumentIngestionRun(enum.StrEnum):
    EN_ATTENTE = "EN_ATTENTE"
    EN_COURS = "EN_COURS"
    A_VALIDER = "A_VALIDER"
    TERMINE = "TERMINE"
    ERREUR = "ERREUR"
    ANNULE = "ANNULE"


class CurrentStep(enum.StrEnum):
    UPLOAD = "UPLOAD"
    DOCUMENT_CLASSIFICATION = "DOCUMENT_CLASSIFICATION"
    OCR_PROOF = "OCR_PROOF"
    LAYOUT_PARSE = "LAYOUT_PARSE"
    FACT_EXTRACTION = "FACT_EXTRACTION"
    DETERMINISTIC_VALIDATION = "DETERMINISTIC_VALIDATION"
    LLM_DRAFT_PACK = "LLM_DRAFT_PACK"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    PROMOTION = "PROMOTION"
    DONE = "DONE"


class StatutStylePack(enum.StrEnum):
    BROUILLON = "BROUILLON"
    ACTIF = "ACTIF"
    ARCHIVE = "ARCHIVE"


class DecisionEditorialeStyleRule(enum.StrEnum):
    A_VALIDER = "A_VALIDER"
    APPROUVEE = "APPROUVEE"
    DESACTIVEE = "DESACTIVEE"


class OrigineStyleRule(enum.StrEnum):
    LLM = "LLM"
    HUMAIN = "HUMAIN"
    MODIFIEE = "MODIFIEE"


class ExtractionMethod(enum.StrEnum):
    EXTRACT = "EXTRACT"
    DERIVE = "DERIVE"


class StatutTechnicalFactCandidate(enum.StrEnum):
    EXTRACTED = "EXTRACTED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    REJECTED = "REJECTED"
    PROMOTED = "PROMOTED"


class TechnicalReviewCaseType(enum.StrEnum):
    CLASSIFICATION_UNCERTAIN = "CLASSIFICATION_UNCERTAIN"
    LOW_OCR_QUALITY = "LOW_OCR_QUALITY"
    DOCUMENT_UNREADABLE = "DOCUMENT_UNREADABLE"
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    VALUE_OUT_OF_RANGE = "VALUE_OUT_OF_RANGE"
    EXACT_MATCH_FAILED = "EXACT_MATCH_FAILED"
    CONTRADICTION = "CONTRADICTION"
    LLM_SELF_CHECK_FLAG = "LLM_SELF_CHECK_FLAG"


class TechnicalReviewTriggerSource(enum.StrEnum):
    CLASSIFIER = "CLASSIFIER"
    OCR = "OCR"
    CUSTOM_EXTRACTOR = "CUSTOM_EXTRACTOR"
    PYTHON_VALIDATOR = "PYTHON_VALIDATOR"
    LLM_SELF_CHECK = "LLM_SELF_CHECK"


class TechnicalReviewSeverity(enum.StrEnum):
    BLOCKING = "BLOCKING"
    WARNING = "WARNING"


class TechnicalReviewStatus(enum.StrEnum):
    A_TRAITER = "A_TRAITER"
    APPROUVE = "APPROUVE"
    CORRIGE = "CORRIGE"
    REJETE = "REJETE"
    DOCUMENT_A_REMPLACER = "DOCUMENT_A_REMPLACER"


class TechnicalReviewResolutionAction(enum.StrEnum):
    APPROVE_DETECTED_VALUE = "APPROVE_DETECTED_VALUE"
    CORRECT_VALUE = "CORRECT_VALUE"
    REJECT_VALUE = "REJECT_VALUE"
    REQUEST_NEW_DOCUMENT = "REQUEST_NEW_DOCUMENT"


class TechnicalFactValidationSource(enum.StrEnum):
    SYSTEM = "SYSTEM"
    HUMAN = "HUMAN"


class ProductSheetGenerationStatus(enum.StrEnum):
    EN_COURS = "EN_COURS"
    TERMINE = "TERMINE"
    A_VALIDER = "A_VALIDER"
    ERREUR = "ERREUR"
